name: Test Backend

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      working-directory: ./demo
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          echo "requirements.txt not found"
          exit 1
        fi

    - name: Run tests
      working-directory: ./demo/backend
      run: |
        # Copy database files and set up automatic cleanup
        cp db/persona_db/*.db db/ || true
        trap 'rm -f db/*.db' EXIT  # Ensures cleanup even if tests fail
        
        # Run pytest with verbose output
        python -m pytest test.py -v
